#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Build the documentation site from a filtered copy of docs/ and check it.

Internal material (docs/plans, docs/internal) and the whitepaper sources are
left out *before* generation, so they cannot reach pages, the search index
or the sitemap. The built site must contain exactly the pages in the
zensical.toml nav (plus 404.html), and every relative link, fragment and
asset must resolve inside the site.

Usage (from the repository root, with the docs dependency group installed):
  python scripts/build_docs.py [--out site]

Nothing is deployed. --out must be a generated-output destination: <root>/site
or a path outside the checkout that is new, empty, or a site this script built
before. The site is built and checked in a staging directory first; only then
is --out replaced.
"""

from __future__ import annotations

import argparse
import json
import posixpath
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from collections.abc import Callable
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit

EXCLUDED_SOURCES = ("plans", "internal", "whitepaper")
FORBIDDEN_SUFFIXES = (".md", ".tex", ".pdf", ".gitkeep", ".gitignore", ".py")
# zensical's skip link (a.md-skip) targets the page's first heading anchor; on a page
# without one (404.html) it falls back to "#__skip", which no element carries.
THEME_SKIP_LINK = "#__skip"
HEADINGS = ("h1", "h2", "h3", "h4", "h5", "h6")


class DocsCheckError(Exception):
    """The built site failed a check."""


def check(condition: bool, message: str) -> None:
    if not condition:
        raise DocsCheckError(message)


def nav_routes(config: dict[str, object]) -> set[str]:
    """Routes ('' for the home page, 'a/b/' otherwise) of every nav entry."""
    routes: set[str] = set()

    def visit(node: object) -> None:
        if isinstance(node, list):
            for item in node:
                visit(item)
        elif isinstance(node, dict):
            for value in node.values():
                visit(value)
        elif isinstance(node, str):
            check(node.endswith(".md"), f"unexpected nav entry {node!r}")
            stem = node.removesuffix(".md")
            routes.add("" if stem == "index" else stem.removesuffix("/index") + "/")

    visit(config["nav"])
    return routes


def _is_generated_site(path: Path, config: dict[str, object]) -> bool:
    """True for a directory this script built before for this project."""
    site_url = str(config.get("site_url", "")).rstrip("/")
    sitemap = path / "sitemap.xml"
    return (
        bool(site_url)
        and sitemap.is_file()
        and (path / "search.json").is_file()
        and f"<loc>{site_url}/" in sitemap.read_text(encoding="utf-8", errors="replace")
        and not (path / ".git").exists()
        and not (path / "zensical.toml").exists()
    )


def check_destination(root: Path, out: Path, config: dict[str, object]) -> Path:
    """Refuse any --out whose replacement could delete source; return the resolved path."""
    check(not out.is_symlink(), f"--out {out} is a symlink; pass the real directory")
    root_res = root.resolve()
    out_res = out.resolve()
    check(
        out_res != root_res and not root_res.is_relative_to(out_res),
        f"--out {out} is the checkout or one of its parent directories",
    )
    if out_res.is_relative_to(root_res):
        check(
            out_res == root_res / "site",
            f"--out {out} is inside the checkout; only {root_res / 'site'} may be used there",
        )
    if out_res.exists():
        check(out_res.is_dir(), f"--out {out} exists and is not a directory")
        check(
            not any(out_res.iterdir()) or _is_generated_site(out_res, config),
            f"--out {out} exists and is not a site generated by this script; remove it or choose "
            "another path",
        )
    return out_res


def build(
    root: Path,
    out: Path,
    validate: Callable[[Path, dict[str, object]], object] | None = None,
) -> dict[str, object]:
    """Build from a filtered copy of docs/ and move the result to *out*.

    *out* is checked before anything is built or deleted. With *validate*, the
    staged site is checked before it replaces *out*.
    """
    config: dict[str, object] = tomllib.loads((root / "zensical.toml").read_text(encoding="utf-8"))[
        "project"
    ]
    out_res = check_destination(root, out, config)
    with tempfile.TemporaryDirectory(prefix="docs-build-") as tmp:
        stage = Path(tmp)
        shutil.copy2(root / "zensical.toml", stage / "zensical.toml")
        docs = root / "docs"
        shutil.copytree(
            docs,
            stage / "docs",
            ignore=lambda d, names: [n for n in names if Path(d) == docs and n in EXCLUDED_SOURCES],
        )
        subprocess.run(
            [sys.executable, "-m", "zensical", "build"], cwd=stage, check=True, stdout=sys.stderr
        )
        if validate is not None:
            validate(stage / "site", config)
        if out_res.exists():
            shutil.rmtree(out_res)
        out_res.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(stage / "site", out_res)
    return config


class _Page(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ids: set[str] = set()
        self.links: list[str] = []
        self.heading_ids: set[str] = set()
        self.theme_skip_links: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        classes = next((v or "" for n, v in attrs if n == "class"), "").split()
        for name, value in attrs:
            if value is None:
                continue
            if name in ("id", "name"):
                self.ids.add(value)
                if tag in HEADINGS:
                    self.heading_ids.add(value)
            elif name in ("href", "src"):
                if tag == "a" and value == THEME_SKIP_LINK and "md-skip" in classes:
                    self.theme_skip_links.append(value)
                else:
                    self.links.append(value)


def _target_file(site: Path, page_url: str, link_path: str) -> Path:
    resolved = posixpath.normpath(posixpath.join(posixpath.dirname(page_url), link_path))
    check(not resolved.startswith(".."), f"{page_url}: link {link_path!r} leaves the site")
    target = site / resolved
    return target / "index.html" if target.is_dir() else target


def check_site(site: Path, config: dict[str, object]) -> dict[str, object]:
    routes = nav_routes(config)
    base = urlsplit(str(config["site_url"])).path.rstrip("/") + "/"
    pages = {p.relative_to(site).as_posix() for p in site.rglob("*.html")}
    expected = {f"{r}index.html" for r in routes} | {"404.html"}
    check(pages == expected, f"built pages differ from nav: {sorted(pages ^ expected)}")
    for item in site.rglob("*"):
        rel = item.relative_to(site).as_posix()
        check(not rel.endswith(FORBIDDEN_SUFFIXES), f"non-site file in output: {rel}")
        check(rel.split("/")[0] not in EXCLUDED_SOURCES, f"excluded material in output: {rel}")

    search = json.loads((site / "search.json").read_text(encoding="utf-8"))
    locations = {item["location"].split("#")[0] for item in search["items"]}
    check(locations <= routes, f"search index has non-nav pages: {sorted(locations - routes)}")
    check(locations == routes, f"search index misses pages: {sorted(routes - locations)}")
    sitemap = re.findall(r"<loc>([^<]*)</loc>", (site / "sitemap.xml").read_text(encoding="utf-8"))
    site_url = str(config["site_url"]).rstrip("/") + "/"
    check(sorted(sitemap) == sorted(site_url + r for r in routes), f"sitemap differs: {sitemap}")

    parsed: dict[str, _Page] = {}
    for rel in sorted(pages):
        parser = _Page()
        parser.feed((site / rel).read_text(encoding="utf-8"))
        parsed[rel] = parser
    links = 0
    for rel, page in parsed.items():
        # The theme's fallback is expected only where there is no heading anchor to target.
        skip_links = page.theme_skip_links if page.heading_ids else []
        for link in page.links + skip_links:
            parts = urlsplit(link)
            if parts.scheme or parts.netloc or link.startswith("mailto:"):
                continue
            path = parts.path
            if path.startswith("/"):
                check(path.startswith(base), f"{rel}: {link!r} is outside {base}")
                path = posixpath.relpath(path, posixpath.dirname(base + rel))
            target = _target_file(site, rel, path) if path else site / rel
            check(target.is_file(), f"{rel}: broken link {link!r}")
            if parts.fragment and target.suffix == ".html":
                target_rel = target.relative_to(site).as_posix()
                check(parts.fragment in parsed[target_rel].ids, f"{rel}: missing anchor {link!r}")
            links += 1
    return {"pages": sorted(pages), "search_locations": sorted(locations), "links_checked": links}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out", type=Path, default=Path("site"))
    args = parser.parse_args(argv)
    result: dict[str, object] = {}

    def validate(site: Path, config: dict[str, object]) -> None:
        result.update(check_site(site, config))

    try:
        build(Path.cwd(), args.out, validate)
    except DocsCheckError as exc:
        print(f"build_docs: FAIL: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
