name: OpenSSF Scorecard

on:
  schedule:
    - cron: "0 6 * * 6" # Saturdays at 06:00 UTC
  push:
    branches: [main]

permissions: {}

jobs:
  scorecard:
    uses: Project-Navi/.github/.github/workflows/scorecard.yml@6c4c2d8f200b1b9c3bd651ebc297425e45d5934e
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
    secrets: inherit
