name: OpenSSF Scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6" # Saturdays at 06:00 UTC
  push:
    branches: [main]

permissions: {}

jobs:
  scorecard:
    uses: Project-Navi/.github/.github/workflows/scorecard.yml@e657c49944bf28e4b04c479ee722c4f6c4e10a9f
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
