name: OpenSSF Scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6" # Saturdays at 06:00 UTC
  push:
    branches: [main]

permissions: {}

jobs:
  scorecard:
    uses: Project-Navi/.github/.github/workflows/scorecard.yml@e4ab481f05f8d1129332dc7186ded2467219ef24
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
